server.error.include-message=always
server.error.include-binding-errors=always

spring.datasource.url=jdbc:postgresql://dpg-d7uua5db910c73evmgig-a:5432/cloudpost
spring.datasource.username=cloudpost_user
spring.datasource.password=LNKVkOPQBAyhDgZn4VrW73wHC3Zo2T8O

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

mybatis.configuration.map-underscore-to-camel-case=true